version: "3.4"

services:

  nginx:
    build:
      context: "./nginx"
    hostname: "cm_nginx"
    ports:
     - "${HTTP_PORT:-80}:80"
    volumes:
     - "app_code:/app"
    depends_on:
     - "php"
    environment:
      PS1: "\\u@\\h:\\w\\$$ "


  db:
    build:
      context: "./db"
    restart: always
    environment:
     - DB_PASS=qqq
    volumes:
      - db_data:/var/lib/postgresql/data

  php:
    build:
      context: "./php"
    hostname: "cm_php"
    volumes:
     - "app_code:/app"
    environment:
      PS1: "\\u@\\h:\\w\\$$ "

volumes:
  app_code:
  db_data:
